#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0-or-later

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  publish_date=""
  fs_address=""
  fs_version=""
  deployments_dir=""
  wallet_name=""
  wallet_path=""
  wallet_password=""
  wallet_seed=""
  target_network=""
  api_key=""
  upload_method=""
  cache_dir=""
  target_file=""
  command_args=()
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    'evm-contract-call' \
    'evm-contracts-tools'
  _check_cmd \
    'evm-contract-deployment-address' \
    'evm-contracts-tools'
  _check_cmd \
    'evm-wallet'
  _check_cmd \
    'bin2txt' \
    'encoding-tools'
  _check_cmd \
    'txt2bin' \
    'encoding-tools'
}

_get_conf_dir_path() {
  local \
    _dir
  _dir="${HOME}/.config/$( \
    _get \
      "app" \
      "name")"
  echo \
    "${_dir}"
}

_cache_dir_auto_detect() {
  local \
    _dir
  _dir="${HOME}/.cache/$( \
    _get \
      "app" \
      "name")"
  echo \
    "${_dir}"
}

_node_run() {
  local \
    _cmd="${1}" \
    _args=() \
    _node_path \
    _lib
  shift \
    1
  _args=(
    "$@"
  )
  _lib="$( \
    _get_lib)"
  _node_path="${_lib}/node_modules" 
  export \
    NODE_PATH="${_node_path}"
  if [[ "${quiet}" != "y" ]]; then
    _args+=(
      -v
    )
  fi
  NODE_PATH="${_node_path}" \
  node \
    "${_cmd}" \
      "${_args[@]}" || \
    true
}

_file_size_check() {
  local \
    _file="${1}" \
    _size
  _size="$( \
    du \
      -b \
      "${_file}")"
  if [[ 23000 < "${_size}" ]]; then
    _msg_info \
      "writing over more than a single string!"
  fi
}

_chunk_verify() {
  local \
    _contract="${1}" \
    _namespace="${2}" \
    _sum="${3}" \
    _index="${4}" \
    _payload="${6}" \
    _uploaded \
    _verify_dir
  _verify_dir="${_cache_dir}/${_sum}/verify"
  mkdir \
    -p \
    "${_verify_dir}"
  evm-c
}

_sum_get() {
  local \
    _content="${1}" 
  echo \
    "${_content}" | \
    sha256sum | \
      awk \
        '{print $1}'
}

_file_hash() {
  local \
    _file="${1}" \
    _content
  _content="$( \
    cat \
      "${_file}")"
  _sum="$( \
    _sum_get \
      "${_content}")"
  echo \
   "${_sum}" 
}

_chunk_publish() {
  local \
    _chunk="${1}"
  evm-contract-call \
    "${_call_opts[@]}" \
    "${_uri_contract}" \
    "publishChunk" \
    "${_uri_namespace}" \
    "${_uri_hash}" \
    "${_chunk}"

}

_file_upload() {
  local \
    _contract="${1}" \
    _namespace="${2}" \
    _file="${3}" \
    _msg=() \
    _sum \
    _length \
    _queue=() \
    _total_chunks \
    _chunk \
    _payload \
    _chunk_prefix \
    _tmp_dir \
    _evm_contract_call_opts=()
  _evm_contract_call_opts+=(
    -n
      "${_target_network}"
    -t
      "dynamic"
    -k
      "${_api_key_path}"
    -N
      "${_wallet_name}"
    # TODO: use locally generated
    #       ABI and bytecode
    # -A
    #   "${_contract_abi}"
  )
  _sum="$( \
    _file_hash \
      "${_file}")"
  _tmp_dir="${_cache_dir}/${_sum}"
  mkdir \
    -p \
    "${_tmp_dir}"
  _chunk_prefix="$( \
    mktemp \
      -p \
        "${_tmp_dir}" \
      --suffix=".base64")"
  _length="22000"
  _file_size_check \
    "${_file}"
  bin2txt \
    -L \
      "${_length}" \
    "${_file}" \
    "${_chunk_prefix}"
  _queue+=( $( \
    find \
      "${_chunk_prefix}"* | \
      sort \
        -V)
  )
  if [[ "${_queue[*]}" == "" ]]; then
    _msg_error \
      "error processing file for upload" \
      1
  fi
  _total_chunks="${#_queue[@]}"
  _i=0
  for _chunk \
    in "${_queue[@]}"; do
    _payload="$( \
      cat \
        "${_chunk}")"
    _msg=(
      "sending chunk '${_chunk}'"
      "of ${_total_chunks}"
    )
    _msg_info \
      "${_msg[*]}"
    _chunk_publish \
      "${_contract}" \
      "${_namespace}" \
      "${_sum}" \
      "${_i}" \
      "${_payload}"
    _i="$(( \
      _i + 1))"
  done
  _i=0
  for _chunk \
    in "${_queue[@]}"; do
    _payload="$( \
      cat \
        "${_chunk}")"
    _msg=(
      "verifying chunk '${_chunk}'"
      "of ${_total_chunks}"
    )
    _msg_info \
      "${_msg[*]}"
    _chunk_verify \
      "${_contract}" \
      "${_namespace}" \
      "${_sum}" \
      "${_i}" \
      "${_payload}"
    _i="$(( \
      _i + 1))"
  done
  _msg=(
    "file '${_file}' uploaded and"
    "available at URI"
    "'evmfs://${_contract}/${_namespace}/${_sum}'")
  _msg_info \
    "${_msg[*]}"
}

_bulk_chunk_publish() {
  local \
    _contract="${1}" \
    _namespace="${2}" \
    _sum="${3}" \
    _index="${4}" \
    _chunk="${5}" \
    _publish \
    _publish_args=()
  _publish="$( \
    _get_lib)/evmfs/publish"
  _publish_args+=(
    "${_contract}"
    "${_namespace}"
    "${_sum}"
    "${_index}"
    "${_chunk}"
  )
  _node_run \
    "${_publish}" \
    "${_publish_args[@]}"
}

_evmfs_publish() {
  local \
    _target_contract="${1}" \
    _wallet_name="${2}" \
    _wallet_path="${3}" \
    _wallet_password="${4}" \
    _wallet_seed="${5}" \
    _target_network="${6}" \
    _api_key_path="${7}" \
    _upload_method="${8}" \
    _cache_dir="${9}" \
    _target_file="${10}" \
    _command_args=() \
    _cmd \
    _args=() \
    _namespace
  shift \
    10
  _command_args+=(
    "$@"
  )
  _namespace="$( \
    evm-wallet \
     get \
       "${_wallet_name}" \
       "address")"
  if [[ "${_upload_method}" == "standalone" ]]; then
    _file_upload \
      "${_target_contract}" \
      "${_namespace}" \
      "${_target_file}"
  fi
}

_wallet_path_get() {
  local \
    _path \
    _name
  _name="$( \
    _get \
      "wallet" \
      "name")"
  _path="$( \
    _get_conf_dir_path)/${_name}.dat"
  echo \
    "${_path}"
}

_secret_get() {
  local \
    _secret="${1}" \
    _path \
    _name
  _name="$( \
    _get \
      "wallet" \
      "name")"
  _path="$( \
    _get_conf_dir_path)/${_name}-${_secret}.txt"
  echo \
    "${_path}"
}

_api_key_get() {
  local \
    _name="${1}" \
    _network="${2}" \
    _conf_dir \
    _service
  if [[ "${_network}" == "ethereum" ]]; then
    _service="etherscan"
  elif [[ "${_network}" == "gnosis" ]]; then
    _service="gnosisscan"
  fi
  _conf_dir="${HOME}/.config/${_service}"
  mkdir \
    -p \
    "${_conf_dir}"
  echo \
    "${_conf_dir}/${_name}.txt"
}

_secret_auto_detect() {
  local \
    _secret="${1}" \
    _secret_type="${2}" \
    _dir \
    _key_gen_opts=() \
    _msg=()
  _path="$( \
    _secret_get \
      "${_secret}")"
  _dir="$( \
    dirname \
      "${_path}")"
  if [[ ! -e "${_path}" ]]; then
    _key_gen_opts+=(
      -t
        "${_secret_type}"
    )
    _msg=(
      "generating ${_secret} '${_path}'"
    )
    if [[ "${quiet}" == "n" ]]; then
      _msg_info \
        "${_msg[*]}"
    fi
    mkdir \
      -p \
      "${_dir}"
    chmod \
      700 \
      "${_dir}"
    chmod \
      700 \
      "${_dir}"
    key-gen \
      "${_key_gen_opts[@]}" \
      "${_path}"
    chmod \
      400 \
      "${_path}"
    _msg=(
      "${_secret} '${_path}' successfully generated"
    )
    if [[ "${quiet}" == "n" ]]; then
      _msg_info \
        "${_msg[*]}"
    fi
  fi
  _set_override \
    "wallet" \
    "${_secret}" \
    "${_path}"
}

_evmfs_contract_auto_detect() {
  local \
    _contract \
    _network \
    _evmfs_address_opts=() \
    _msg=()
  _network="$( \
    _get \
      "target" \
      "network")"
  _evmfs_address_opts+=(
    -n
      "${_network}"
  )
  _contract="$( \
    evm-contract-deployment-address \
      -a
    evmfs-address \
      "${_evmfs_address_opts[@]}")"
  if [[ "${_contract}" == "" ]]; then
    _msg=(
      "error getting default contract"
      "address for network"
      "'${_network}'"
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  _set_override \
    "target" \
    "contract" \
    "${_contract}"
}

_set_overrides() {
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "publish" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "wallet" \
    "name" \
    "default"
  _set_override \
    "target" \
    "network" \
    "gnosis"
  _evmfs_contract_auto_detect
  _set_override \
    "api" \
    "key" \
    "$(_api_key_get \
         "default" \
         "$(_get \
              "target" \
              "network")")"
  _set_override \
    "wallet" \
    "path" \
    "$(_wallet_path_get)"
  _secret_auto_detect \
    "seed" \
    "seed"
  _secret_auto_detect \
    "password" \
    "plain"
  _set_override \
    "wallet" \
    "address" \
    "$(evm-wallet \
         get \
           "${wallet_name}" \
           "address")"
  _set_override \
    "cache" \
    "dir" \
    "$(_cache_dir_auto_detect)"
  _set_override \
    "upload" \
    "method" \
    "standalone"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
EVM network file system file publisher

Usage:
  $(_get "app" "name")
    [options]
    <file>
  networks:
    alchemy
    ankr
    cloudflare
    chainstack
    etherscan
    gnosis
    infura
    publicPolygon
    quicknode
  options:
     -A <fs_address>      Address of the EVM file system
                          on the network.
                          Default: $(_get "fs" "address")
     -n <wallet_name>     Wallet name.
                          Default: $(_get "wallet" "name")
     -w <wallet_path>     Wallet path.
                          Default: $(_get "wallet" "path")
     -p <wallet_password> Wallet password.
                          Default: $(_get "wallet" "password")
     -s <wallet_seed>     Wallet seed path.
                          Default: $(_get "wallet" "seed")
     -n <network>         EVM network name ('mainnet', 'gnosis').
                          Default: $(_get "target" "network")
     -k <api_key>         Etherscan-like service key.
                          Default: $(_get "api" "key")
     -m <upload_method>   It can be 'standalone' or 'bulk'
                          Default: $(_get "upload" "method")
     -C <cache_dir>       Work directory
                          Default: $(_get "cache" "dir")

     -h                   This message.
     -c                   Enable color output
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_display_flags() {
  local \
    _flags=(
      "${1}"
    ) \
    _flag
  for _flag \
    in "${_flags[@]}"; do
  _msg_info \
    "                             ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "             Publish date:   $(_get "publish" "date")"
  _msg_info "      File system address:   $(_get "fs" "address")"
  _msg_info "      File system version:   $(_get "fs" "version")"
  _msg_info "    Deployments directory:   $(_get "deployments" "dir")"
  _msg_info "                Namespace:   $(_get "wallet" "address")"
  _msg_info "              Wallet name:   $(_get "wallet" "name")"
  _msg_info "              Wallet path:   $(_get "wallet" "path")"
  _msg_info "          Wallet password:   $(_get "wallet" "password")"
  _msg_info "              Wallet seed:   $(_get "wallet" "seed")"
  _msg_info "           Target network:   $(_get "target" "network")"
  _msg_info "                  API key:   $(_get "api" "key")"
  _msg_info "            Upload method:   $(_get "upload" "method")"
  _msg_info "          Cache directory:   $(_get "cache" "dir")"
  _msg_info "              Target file:   $(_get "target" "file")"
}

_globals
_global_variables
_requirements
_config_user_init \
  "$(_get \
       "app" \
       "name")"
# shellcheck disable=SC2034
while \
  getopts \
    'A:V:d:N:w:p:s:n:k:m:cvh?' \
    arg; do
  case \
    "${arg}" in
    A) override_fs_address="${OPTARG}" ;;
    V) override_fs_version="${OPTARG}" ;;
    d) override_deployments_dir="${OPTARG}" ;;
    N) override_wallet_name="${OPTARG}" ;;
    w) override_wallet_path="${OPTARG}" ;;
    p) override_wallet_password="${OPTARG}" ;;
    s) override_wallet_seed="${OPTARG}" ;;
    n) override_target_network="${OPTARG}" ;;
    k) override_api_key="${OPTARG}" ;;
    m) override_upload_method="${OPTARG}" ;;
    C) override_cache_dir="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( 0 < $# )); then
  _set \
    "target" \
    "file" \
    "${1}"
fi
shift \
  1 || \
  true
command_args+=(
  "$@"
)
_set_overrides
_config_user_init \
  "$( \
    _get \
      "app" \
      "name")"
_show_config
app_opts=(
  "$(_get \
       "fs" \
       "address")"
  "$(_get \
       "fs" \
       "version")"
  "$(_get \
       "deployments" \
       "dir")"
  "$(_get \
       "wallet" \
       "name")"
  "$(_get \
       "wallet" \
       "path")"
  "$(_get \
       "wallet" \
       "password")"
  "$(_get \
       "wallet" \
       "seed")"
  "$(_get \
       "target" \
       "network")"
  "$(_get \
       "api" \
       "key")"
  "$(_get \
       "cache" \
       "dir")"
  "$(_get \
       "upload" \
       "method")"
  "$(_get \
       "cache" \
       "dir")"
  "$(_get \
       "target" \
       "file")"
)
_evmfs_publish \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
