#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0-or-later

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  resolve_date=""
  target_network=""
  network_id=""
  fs_version=""
  user_defined=""
  color=""
  quiet=""
}

_requirements() {
  true
}

_contract_address_get() {
  local \
    _deployments_path="${1}" \
    _network="${2}" \
    _fs_version="${3}" \
    _config
  _config="${_deployments_path}/config.sh"
  source 
}

_network_check() {
  local \
    _target_network="${1}" \
    _target_network_id="${2}" \
    _msg=()
  if [[ "${_target_network}" == "gnosis" ]]; then
    _network_id="100"
  else
    _msg=(
      "no Ethereum Virtual Machine file system"
      "deployed on network '${_target_network}'"
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  if [[ "${_target_network_id}" != "" ]]; then
    if [[ "${_target_network_id}" != "${_network_id}" ]]; then
    _msg=(
      "requested target network ID"
      "'${_target_network_id}' does"
      "not correspond to '${_target_network}'"
      "known ID '${_network_id}'"
    )
    _msg_error \
      "${_msg[*]}" \
      1
    fi
  fi
}

_user_deployments_init() {
  mkdir \
    -p \
    "${_deployments_path}"
  chmod \
    700 \
    "${_deployments_path}"
  cp \
    -r \
    "$(_fs_deployments_path_get \
         "system")/"* \
    "${_deployments_path}"
}

_user_deployments_check() {
   if [[ ! -e "${_deployments_path}" ]]; then
     _user_deployments_init
   fi
}

_evmfs_address() {
  local \
    _target_network="${1}" \
    _target_network_id="${2}" \
    _fs_version="${3}" \
    _user_defined="${4}" \
    _deployments_path="${5}" \
    _system_deployments_path \
    _user_deployments_path \
    _network_id \
    _contract_address \
    _args=() \
    _msg=()
  shift \
    2
  _args+=(
    "$@"
  )
  _network_check \
    "${_target_network}" \
    "${_target_network_id}"
  if [[ "${_user_defined}" == "n" ]]; then
    _system_deployments_path="$( \
      _fs_deployments_path_get \
        "system")"
    if [[ "${_deployments_path}" != "${_system_deployments_path}" ]]; then
      _msg=(
        "to set a custom deployments path"
        "you need to enable the user-defined"
        "deployments switch with '-u'"
      )
      _msg_error \
        "${_msg[*]}" \
        1
    fi
    _network_check \
      "${_target_network}" \
      "${_target_network_id}" \
      "${_fs_version}"
  elif [[ "${_user_defined}" == "y" ]]; then
    _user_deployments_path="$( \
      _fs_deployments_path_get \
        "user")"
    if [[ "${_deployments_path}" != "${_user_deployments_path}" ]]; then
      _msg=(
        "using custom deployments path"
        "'${_deployments_path}'"
      )
      _msg_info \
        "${_msg[*]}"
    elif [[ "${_deployments_path}" == "${_user_deployments_path}" ]]; then
      _user_deployments_check
    fi
  fi
  _contract_address_get \
    "${_deployments_path}" \
    "${_target_network}" \
    "${_fs_version}"
  echo \
    "${_contract_address}"
}

_fs_deployments_path_get() {
  local \
    _type="${1}" \
    _conf_dir
  if [[ "${_type}" == "system" ]]; then
    _conf_dir="$( \
      _get_lib)"
  elif [[ "${_type}" == "user" ]]; then
    _conf_dir="${HOME}/.config"
  fi
  echo \
    "${_conf_dir}/evmfs/deployment"
}

_deployments_path_auto_detect() {
  local \
    _deployments \
    _user_defined
  _user_defined="$( \
    _get \
      "user" \
      "defined")"
  if [[ "${_user_defined}" == "n" ]]; then
    _deployments="$( \
      _fs_deployments_path \
        "system")"
  elif [[ "${_user_defined}" == "y" ]]; then
    _deployments="$( \
      _fs_deployments_path \
        "system")"
  fi
  _set_override \
    "deployments" \
    "dir" \
    "${_deployments}"
}

_set_overrides() {
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "resolve" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "target" \
    "network" \
    "gnosis"
  _set_override \
    "network" \
    "id" \
    ""
  _set_override \
    "fs" \
    "version" \
    "1"
  _set_override \
    "user" \
    "defined" \
    "n"
  _deployments_path_auto_detect
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Returns an EVM network's file system contract address

Usage:

  $(_get "app" "name")
    [options]

  networks:
    gnosis

  options:
     -n <network>         EVM network name ('gnosis').
                          Default: $(_get "target" "network")
     -i <network_id>      EVM network id.
                          Default: $(_get "network" "id")
     -V <fs_version>      File system's contract vesion.
                          Default: $(_get "fs" "version")
     -u                   Returns contract address for
                          user-defined file system
                          deployment instead of the
                          system one.
                          Default: $(_get "user" "defined")
     -d                   Specify contracts deployments path
                          Default: $(_get "deployments" "path")


     -h                   This message.
     -c                   Enable color output
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_display_flags() {
  local \
    _flags=(
      "${1}"
    ) \
    _flag
  for _flag \
    in "${_flags[@]}"; do
  _msg_info \
    "                             ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "             Resolve date:   $(_get "resolve" "date")"
  _msg_info "           Target network:   $(_get "target" "network")"
  _msg_info "               Network ID:   $(_get "network" "id")"
  _msg_info "      File System version:   $(_get "fs" "version")"
  _msg_info "     User-defined address:   $(_get "user" "defined")"
  _msg_info "         Deployments path:   $(_get "deployments" "path")"
}

_globals
_global_variables
_requirements
_config_user_init \
  "$(_get \
       "app" \
       "name")"
# shellcheck disable=SC2034
while \
  getopts \
    'n:i:V:ud:cvh?' \
    arg; do
  case \
    "${arg}" in
    n) override_target_network="${OPTARG}" ;;
    i) override_network_id="${OPTARG}" ;;
    V) override_fs_version="${OPTARG}" ;;
    u) override_user_defined="y" ;;
    d) override_deployments_path="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
_set_overrides
_config_user_init \
  "$( \
    _get \
      "app" \
      "name")"
_show_config
app_opts=(
  "$( \
    _get \
      "target" \
      "network")"
  "$( \
    _get \
      "network" \
      "id")"
  "$( \
    _get \
      "fs" \
      "version")"
  "$( \
    _get \
      "user" \
      "defined")"
  "$( \
    _get \
      "deployments" \
      "path")"
)
_evmfs_address \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
