#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

//    ----------------------------------------------------------------------
//    Copyright © 2024, 2025  Pellegrino Prevete
//
//    All rights reserved
//    ----------------------------------------------------------------------
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.

const
  _libcrash =
  require(
    '../libcrash-js/crash-js');
_dirname =
  _libcrash._dirname;
_file_read =
  _libcrash._file_read;
_path_join =
  _libcrash._path_join;
_msg_info =
  _libcrash._msg_info;
_msg_error =
  _libcrash._msg_error;
const
  _evm_contract_call_dynamic_module =
    require(
      '../evm-contracts-tools/evm-contract-call-dynamic');
_contract_run =
  _evm_contract_call_dynamic_module._contract_run;
const
  _evm_contract_call_static_module =
    require(
      '../evm-contracts-tools/evm-contract-call-static');
_contract_call_static =
  _evm_contract_call_static_module._contract_call_static;
const
  _get_module =
    require(
      "./get");
_get =
  _get_module._get;

function
  _global_variables() {
  retries_max =
    '';
  wallet_seed_path =
    "";
  api_key_path =
    "";
  target_network =
    "";
  contract_address =
    "";
  contract_abi_path =
    "";
  contract_bytecode_path =
    "";
  publication_namespace =
    "";
  file_hash =
    "";
  index_start =
    "";
  index_end =
    "";
  file_chunks =
    [];
  quiet =
    "";
}

function
  _msg_info_chunk_publish(
    _index,
    _progress,
    _total) {
  let
    _msg,
    _template;
  _template =
    "Publishing chunk '{_index}' ('{_progress}'of '{_total}').";
  _msg =
    _template.replaceAll(
      "{_index}",
      _index);
  _msg =
    _msg.replaceAll(
      "{_progress}",
      _progress);
  _msg =
    _msg.replaceAll(
      "{_total}",
      _total);
  _msg_info(
    _msg);
}

function
  _msg_info_chunk_published(
    _index,
    _progress,
    _total) {
  let
    _msg,
    _template;
  _template =
    "Published chunk '{_index}' ('{_progress}'of '{_total}').";
  _msg =
    _template.replaceAll(
      "{_index}",
      _index);
  _msg =
    _msg.replaceAll(
      "{_progress}",
      _progress);
  _msg =
    _msg.replaceAll(
      "{_total}",
      _total);
  _msg_info(
    _msg);
}

async function
  _chunk_publish(
    _index,
    _contract_run_opts) {
  let _tx;
  try {
    _tx = await
      _contract_run.apply(
        null,
        _contract_run_opts);
  } catch(e) {
    _msg_error(
      e,
      1);
  }
  return _tx;
}

function
  _input_data_check(
    _index_start,
    _index_end,
    _total_files) {
  let
    _total_indexes;
  _total_indexes =
    _index_end - _index_start + 1;
  if ( _total_files > _total_indexes ) {
    _msg_error(
      "More files to save into than indexes to download.",
      1);
  }
  if ( _total_files < _total_indexes ) {
    _msg_error(
      "More indexes downloads than files to save into.",
      1);
  }
  _msg_info(
    "Input data checked.");
}

async function
  _publish(
    _retries_max,
    _wallet_seed_path,
    _api_key_path,
    _target_network,
    _contract_address,
    _contract_abi_path,
    _contract_bytecode_path,
    _publication_namespace,
    _file_hash,
    _index_start,
    _index_end,
    _file_chunks
  ) {
  let
    _contract_run_base_opts,
    _contract_run_opts,
    _chunk,
    _file_chunk,
    _file_chunk_path,
    _method_args,
    _msg,
    _index,
    _progress,
    _value,
    _total_chunks,
    _tx,
    _wallet_password;
  _wallet_password =
    "";
  _contract_run_base_opts = [
    _wallet_seed_path,
    _wallet_password,
    _api_key_path,
    _target_network,
    _contract_address,
    _contract_abi_path,
    _contract_bytecode_path,
    "publishChunk",
  ];
  _method_base_args = [
    _publication_namespace,
    _file_hash
  ];
  _total_chunks =
    _file_chunks.length;
  _progress =
    1;
  _cursor =
    0;
  for ( var _index = _index_start;
	_index <= _index_end;
	_index++ ) {
    _msg_info_chunk_publish(
      _index,
      _progress,
      _chunks_total);
    _file_chunk_path =
      _file_chunks[_cursor];
    if ( _file_chunk_path == undefined ) {
      console.error(
        "error with index",
        _index,
        "and cursor",
        _cursor,
        "file_chunk",
        _file_chunks[_cursor]);
      process.exit(1);
    }
    _file_chunk =
      _file_read(
        _file_chunk_path);
    _method_args =
      _method_base_args.concat(
        [_index.toString(),
	 _file_chunk]
      );
    _contract_run_opts =
      _contract_run_base_opts.concat(
        [_method_args]);
    _tx = await
      _chunk_publish(
        _contract_run_opts);
    _msg_info_chunk_published(
      _chunk,
      _total_chunks);
  }
}

function
  _config_show() {
  let
    _file_chunks,
    _line,
    _text;
  _text = 
    [];
  _text.push(
    "      Maximum retries: {retries_max}".replace(
      "{retries_max}",
      retries_max));
  _text.push(
    "          Wallet seed: {wallet_seed_path}".replace(
      "{wallet_seed_path}",
      wallet_seed_path));
  _text.push(
    "              API Key: {api_key_path}".replace(
      "{api_key_path}",
      api_key_path));
  _text.push(
    "       Target network: {target_network}".replace(
      "{target_network}",
      target_network));
  _text.push(
    "     Contract address: {contract_address}".replace(
      "{contract_address}",
      contract_address));
  _text.push(
    "         Contract ABI: {contract_abi_path}".replace(
      "{contract_abi_path}",
      contract_abi_path));
  _text.push(
    "    Contract bytecode: {contract_bytecode_path}".replace(
      "{contract_bytecode_path}",
      contract_bytecode_path));
  _text.push(
    "            File hash: {file_hash}".replace(
      "{file_hash}",
      file_hash));
  _text.push(
    "Publication namespace: {file_hash}".replace(
      "{file_hash}",
      file_hash));
  _text.push(
    "          Index start: {index_start}".replace(
      "{index_start}",
      index_start));
  _text.push(
    "            Index end: {index_end}".replace(
      "{index_end}",
      index_end));
  _file_chunks =
    file_chunks.join(
    " ");
  _text.push(
    "      File chunks: {_file_chunks}".replace(
      "{_file_chunks}",
      _file_chunks));
  for ( _line in _text ) {
    _msg_info(
      _text[_line]);
  }
}

function
  _usage() {
  let
    _line,
    _text;
  _text = [
    "Usage:",
    "  publish",
    "    <quiet>",
    "    <retries_max>",
    "    <wallet_seed_path>",
    "    <api_key_path>",
    "    <target_network>",
    "    <contract_address>",
    "    <contract_abi_path>",
    "    <contract_bytecode_path>",
    "    <publication_namespace>",
    "    <file_hash>",
    "    [file_chunk]",
    "",
    "Args:",
    "  <quiet>                   Can be 'y' or 'n'",
    "                            Default: y",
    "  <retries_max>             Maximum number of retries before",
    "                            failing (not implemented).",
    "  <wallet_seed_path>        Path of the file containing",
    "                            the seed phrase.",
    "  <api_key_path>            Path of the API key for the",
    "                            contract ABI provider service.",
    "  <target_network>          Network on which the contract",
    "                            resides.",
    "  <contract_address>        Address of the contract.",
    "  <contract_abi_path>       Contract ABI path.",
    "  <contract_bytecode_path>  Path for the contract bytecode.",
    "  <publication_namespace>   Namespace in which the file will be",
    "                            published.",
    "  <file_hash>               Hash of the file to publish.",
    "  [file_chunks]             File chunks to publish.",
  ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
  process.exit();
}

function 
  _cmdline_parse() {
  quiet = 
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        retries_max =
          _value;
      }
      if ( _index == 4 ) {
        wallet_seed_path =
          _value;
      }
      if ( _index == 5 ) {
        api_key_path =
          _value;
      }
      if ( _index == 6 ) {
        target_network =
          _value;
      }
      if ( _index == 7 ) {
        contract_address =
          _value;
      }
      if ( _index == 8 ) {
        contract_abi_path =
          _value;
      }
      if ( _index == 9 ) {
        contract_bytecode_path =
          _value;
      }
      if ( _index == 10 ) {
        publication_namespace =
          _value;
      }
      if ( _index == 11 ) {
        file_hash =
          _value;
      }
      if ( _index == 12 ) {
        index_start =
          _value;
      }
      if ( _index == 13 ) {
        index_end =
          _value;
      }
      if ( 13 < _index ) {
	file_chunks.push(
          _value);
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        _usage();
      }
  });
  if ( file_hash == "" ||
       publication_namespace  == "" ||
       file_chunks == [] ) {
    _usage();
  }
}

async function
  _publish_cmdline(
    _app_opts) {
  let
    _chunk,
    _chunks_published;
  _chunks_published = 
    await _publish.apply(
      null,
      _app_opts);
  for ( _chunk in _chunks_published ) {
    process.stdout.write(
      _chunks_published[_chunk].toString());
  }
}

_global_variables();

if ( require.main == module ) {
  _cmdline_parse();
  _config_show();
  app_opts = [
    retries_max,
    wallet_seed_path,
    api_key_path,
    target_network,
    contract_address,
    contract_abi_path,
    contract_bytecode_path,
    publication_namespace,
    file_hash,
    index_start,
    index_end,
    file_chunks,
  ];
  _publish_cmdline.apply(
    null,
    app_opts);
}

module.exports = {
  _publish:
    _publish
};
