#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

//    ----------------------------------------------------------------------
//    Copyright © 2024, 2025  Pellegrino Prevete
//
//    All rights reserved
//    ----------------------------------------------------------------------
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.

const
  _libcrash =
  require(
    '../libcrash-js/crash-js');
_cmdline_check =
  _libcrash._cmdline_check;
_ext_rm =
  _libcrash._ext_rm;
_file_read =
  _libcrash._file_read;
_file_write =
  _libcrash._file_write;
_msg_info =
  _libcrash._msg_info;
_msg_error =
  _libcrash._msg_error;
const
  _evm_contract_call_dynamic_module =
    require(
      '../evm-contracts-tools/evm-contract-call-dynamic');
_contract_run =
  _evm_contract_call_dynamic_module._contract_run;
const
  _check_module =
    require(
      "./check");
_chunk_check =
  _check_module._chunk_check;
const
  _verify_module =
    require(
      './verify');
_verify =
  _verify_module._verify;

function
  _global_variables() {
  app_name =
    "publish";
  retries_max =
    "";
  call_timeout =
    "";
  wallet_seed_path =
    "";
  api_key_path =
    "";
  target_network =
    "";
  contract_address =
    "";
  contract_abi_path =
    "";
  contract_bytecode_path =
    "";
  contract_compiler_output_path =
    "";
  publication_namespace =
    "";
  file_hash =
    "";
  index_start =
    "";
  index_end =
    "";
  checkpoint_file_path =
    "";
  chunks_files_paths =
    [];
  quiet =
    "";
}

function
  _msg_info_chunk_publish(
    _index,
    _progress,
    _total) {
  let
    _msg,
    _template;
  _template =
    "Publishing chunk '{_index}' ('{_progress}'of '{_total}').";
  _msg =
    _template.replaceAll(
      "{_index}",
      _index);
  _msg =
    _msg.replaceAll(
      "{_progress}",
      _progress);
  _msg =
    _msg.replaceAll(
      "{_total}",
      _total);
  _msg_info(
    _msg);
}

function
  _msg_info_chunk_unpublished(
    _index,
    _progress,
    _total) {
  let
    _msg,
    _template;
  _template =
    "Chunk '{_index}' unpublished, publishing now ('{_progress}'of '{_total}').";
  _msg =
    _template.replaceAll(
      "{_index}",
      _index);
  _msg =
    _msg.replaceAll(
      "{_progress}",
      _progress);
  _msg =
    _msg.replaceAll(
      "{_total}",
      _total);
  _msg_info(
    _msg);
}

function
  _msg_info_chunk_published_already(
    _index,
    _progress,
    _total) {
  let
    _msg,
    _template;
  _template =
    "Chunk '{_index}' published already ('{_progress}'of '{_total}').";
  _msg =
    _template.replaceAll(
      "{_index}",
      _index);
  _msg =
    _msg.replaceAll(
      "{_progress}",
      _progress);
  _msg =
    _msg.replaceAll(
      "{_total}",
      _total);
  _msg_info(
    _msg);
}


function
  _msg_info_chunk_published(
    _index,
    _progress,
    _total) {
  let
    _msg,
    _template;
  _template =
    "Published chunk '{_index}' ('{_progress}'of '{_total}').";
  _msg =
    _template.replaceAll(
      "{_index}",
      _index);
  _msg =
    _msg.replaceAll(
      "{_progress}",
      _progress);
  _msg =
    _msg.replaceAll(
      "{_total}",
      _total);
  _msg_info(
    _msg);
}

async function
  _chunk_publish(
    _contract_run_opts) {
  let
    _tx;
  try {
    _tx = await
      _contract_run.apply(
        null,
        _contract_run_opts);
  } catch(e) {
    console.error(
      "Error publishing the chunk.");
    _msg_error(
      e,
      0);
    throw e
  }
  return _tx;
}

function
  _input_data_check(
    _index_start,
    _index_end,
    _total_files) {
  let
    _total_indexes;
  _total_indexes =
    _index_end - _index_start + 1;
  if ( _total_files > _total_indexes ) {
    _msg_error(
      "More files to save into than indexes to download.",
      1);
  }
  if ( _total_files < _total_indexes ) {
    _msg_error(
      "More indexes downloads than files to save into.",
      1);
  }
  _msg_info(
    "Input data checked.");
}

function
  _chunk_file_path_check(
    _path,
    _index,
    _cursor) {
  if ( _path == undefined ) {
    console.error(
      "Chunk file for index",
      _index,
      "and cursor",
      _cursor,
      "undefined.");
    process.exit(
      1);
  }
}

function
  _chunks_files_paths_prefix_get(
    _chunks_unverified) {
  let
    _chunks_files_paths_prefix;
  if ( _chunks_unverified.length != 0 ) {
    if ( _chunks_unverified[0] == undefined ) {
      _msg_error(
        "Weird error.",
        1);
    }
    else if ( _chunks_unverified[0].length != 0 ) {
      _chunks_files_paths_prefix =
        _ext_rm(
          _chunks_unverified[
            0][
              1]);
    }
  }
  else if ( _chunks_unverified.length == 0 ) {
    _msg_info(
      "File already published.");
  }
  return _chunks_files_paths_prefix;
}

async function
  _publish(
    _retries_max,
    _call_timeout,
    _wallet_seed_path,
    _api_key_path,
    _target_network,
    _contract_address,
    _contract_abi_path,
    _contract_bytecode_path,
    _contract_compiler_output_path,
    _publication_namespace,
    _file_hash,
    _index_start,
    _index_end,
    _checkpoint_file_path,
    _chunks_files_paths
  ) {
  let
    _check_call_base_opts,
    _check_call_opts,
    _checkpoint_index,
    _chunk,
    _chunk_check_args,
    _chunk_file_path,
    _chunk_publish_args,
    _chunks_total,
    _chunks_files_paths_prefix,
    _chunks_unverified = [],
    _indexes_unverified = [],
    _method_base_args,
    _progress,
    _publish_call_base_opts,
    _publish_call_opts,
    _published,
    _tx,
    _value,
    _wallet_password;
  if ( _call_timeout == "" ) {
    _call_timeout =
      300;
  }
  _call_timeout =
    Number(
      _call_timeout);
  _index_start =
    Number(
      _index_start);
  _index_end =
    Number(
      _index_end);
  _wallet_password =
    "";
  _check_call_base_opts = [
    "", // _wallet_seed_path,
    _retries_max,
    _api_key_path,
    _target_network,
    _contract_abi_path,
    _contract_bytecode_path,
    _contract_compiler_output_path,
    _contract_address,
    "chunks",
  ];
  _publish_call_base_opts = [
    _retries_max,
    _call_timeout,
    _wallet_seed_path,
    _wallet_password,
    _api_key_path,
    0,
    "ether",
    _target_network,
    _contract_address,
    _contract_abi_path,
    _contract_bytecode_path,
    _contract_compiler_output_path,
    "publishChunk",
  ];
  _method_base_args = [
    _publication_namespace,
    _file_hash
  ];
  _chunks_total =
    _chunks_files_paths.length;
  if ( _chunks_total == 0 ) {
    _msg_error(
      "file chunks list empty",
      1);
  }
  _input_data_check(
    _index_start,
    _index_end,
    _chunks_total);
  _progress =
    1;
  _cursor =
    0;
  for ( var _index = _index_start;
        _index <= _index_end;
        _index++ ) {
    _msg_info_chunk_publish(
      _index,
      _progress,
      _chunks_total);
    _chunk_file_path =
      _chunks_files_paths[
        _cursor];
    _chunk_file_path =
      _chunks_files_paths[
        _cursor];
    _chunk_file_path_check(
      _chunk_file_path,
      _index,
      _cursor);
    _chunk =
      _file_read(
        _chunk_file_path);
    _chunk_check_args =
      _method_base_args.concat(
        [_index.toString()]);
    _check_call_opts =
      _check_call_base_opts.concat(
        [_chunk_check_args]);
    try {
      _published = await
        _chunk_check(
          _chunk,
          _check_call_opts);
    } catch (e) {
      console.error(
        "Error checking publication status.");
      throw e;
    }
    if ( _published == true ) {
      _msg_info_chunk_published_already(
        _index,
        _progress,
        _chunks_total);
    }
    else if ( _published == false ) {
      _msg_info_chunk_unpublished(
        _index,
        _progress,
        _chunks_total);
      _chunk_publish_args =
        _method_base_args.concat(
          [_index.toString(),
           _chunk]);
      _publish_call_opts =
        _publish_call_base_opts.concat(
          [_chunk_publish_args]);
      try {
        _tx = await
          _chunk_publish(
            _publish_call_opts);
      } catch (e) {
        console.error(
          "Error running publishing chunk function.");
	throw e;
      }
      _msg_info_chunk_published(
        _index,
        _progress,
        _chunks_total);
      _chunks_unverified.push(
        [_index,
         _chunk_file_path]);
    }
    else {
      console.error(
        _published);
      throw "Unexpected chunk publication status value.";
    }
    _checkpoint_index =
      _index.toString();
    _file_write(
      _checkpoint_file_path,
      _checkpoint_index);
    _progress =
      _progress + 1;
    _cursor =
      _cursor + 1;
  }
  if ( _chunks_unverified.length != 0 ) {
    _chunks_files_paths_prefix =
      _chunks_files_paths_prefix_get(
        _chunks_unverified);
    for ( _chunk of _chunks_unverified ) {
      _indexes_unverified.push(
        _chunk[
          0]);
    }
  }
  if ( _indexes_unverified.length != 0 ) {
    _msg_info(
      "Some index are left to verify.");
    // _verify(
    //   _retries_max,
    //   _api_key_path,
    //   _target_network,
    //   _contract_address,
    //   _contract_abi_path,
    //   _contract_bytecode_path,
    //   _contract_compiler_output_path,
    //   _publication_namespace,
    //   _file_hash,
    //   _chunks_files_paths_prefix,
    //   _indexes_unverified); 
  }
  else if ( _indexes_unverified.length == 0 ) {
    _msg_info(
      "All chunks already verified.");
    _checkpoint_index =
      _index_end.toString();
    _file_write(
      _checkpoint_file_path,
      _checkpoint_index);
  }
  return _chunks_unverified;
}

function
  _config_show() {
  let
    _chunks_files_paths,
    _line,
    _text;
  _text = 
    [];
  _text.push(
    "          Maximum retries: {retries_max}".replace(
      "{retries_max}",
      retries_max));
  _text.push(
    "            Call timeout: {call_timeout}".replace(
      "{call_timeout}",
      call_timeout));
  _text.push(
    "              Wallet seed: {wallet_seed_path}".replace(
      "{wallet_seed_path}",
      wallet_seed_path));
  _text.push(
    "                  API Key: {api_key_path}".replace(
      "{api_key_path}",
      api_key_path));
  _text.push(
    "           Target network: {target_network}".replace(
      "{target_network}",
      target_network));
  _text.push(
    "         Contract address: {contract_address}".replace(
      "{contract_address}",
      contract_address));
  _text.push(
    "             Contract ABI: {contract_abi_path}".replace(
      "{contract_abi_path}",
      contract_abi_path));
  _text.push(
    "        Contract bytecode: {contract_bytecode_path}".replace(
      "{contract_bytecode_path}",
      contract_bytecode_path));
  _text.push(
    " Contract compiler output: {contract_compiler_output_path}".replace(
      "{contract_compiler_output_path}",
      contract_compiler_output_path));

  _text.push(
    "                File hash: {file_hash}".replace(
      "{file_hash}",
      file_hash));
  _text.push(
    "    Publication namespace: {file_hash}".replace(
      "{file_hash}",
      file_hash));
  _text.push(
    "              Index start: {index_start}".replace(
      "{index_start}",
      index_start));
  _text.push(
    "                Index end: {index_end}".replace(
      "{index_end}",
      index_end));
  _text.push(
    "          Checkpoint file: {checkpoint_file_path}".replace(
      "{checkpoint_file_path}",
      checkpoint_file_path));
  _chunks_files_paths =
    chunks_files_paths.join(
    " ");
  _text.push(
    "              File chunks: {_chunks_files_paths}".replace(
      "{_chunks_files_paths}",
      _chunks_files_paths));
  for ( _line in _text ) {
    _msg_info(
      _text[_line]);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line,
    _text;
  _text = [
    "Usage:",
    "  publish",
    "    <quiet>",
    "    <retries_max>",
    "    <call_timeout>",
    "    <wallet_seed_path>",
    "    <api_key_path>",
    "    <target_network>",
    "    <contract_address>",
    "    <contract_abi_path>",
    "    <contract_bytecode_path>",
    "    <contract_compiler_output_path>",
    "    <publication_namespace>",
    "    <file_hash>",
    "    <index_start>",
    "    <index_end>",
    "    <checkpoint_file_path>",
    "    [chunk_file_path]",
    "",
    "Args:",
    "  <quiet>                          Can be 'y' or 'n'",
    "                                   Default: y",
    "  <retries_max>                    Maximum number of retries before",
    "                                   failing (not implemented).",
    "  <call_timeout>                   How much seconds to wait for a return",
    "                                   before declaring the call failed.",
    "  <wallet_seed_path>               Path of the file containing",
    "                                   the seed phrase.",
    "  <api_key_path>                   Path of the API key for the",
    "                                   contract ABI provider service.",
    "  <target_network>                 Network on which the contract",
    "                                   resides.",
    "  <contract_address>               Address of the contract.",
    "  <contract_abi_path>              Contract ABI path.",
    "  <contract_bytecode_path>         Path for the contract bytecode.",
    "  <contract_compiler_output_path>  Path for the contract compiler",
    "                                   output path (the hardhat artifact).",
    "  <publication_namespace>          Namespace in which the file will be",
    "                                   published.",
    "  <file_hash>                      Hash of the file to publish.",
    "  <index_start>                    Chunk index from where to start.",
    "  <index_end>                      Final chunk index to download.",
    "  <checkpoint_file_path>           Checkpoint file on which latest",
    "                                   downloaded chunk index is saved",
    "                                   in case node was to crash.",
    "  [chunks_files_paths]             File chunks to publish.",
  ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
  process.exit(
    _exit_code);
}

function 
  _cmdline_parse() {
  quiet = 
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        retries_max =
          _value;
      }
      if ( _index == 4 ) {
        call_timeout =
          _value;
      }
      if ( _index == 5 ) {
        wallet_seed_path =
          _value;
      }
      if ( _index == 6 ) {
        api_key_path =
          _value;
      }
      if ( _index == 7 ) {
        target_network =
          _value;
      }
      if ( _index == 8 ) {
        contract_address =
          _value;
      }
      if ( _index == 9 ) {
        contract_abi_path =
          _value;
      }
      if ( _index == 10 ) {
        contract_bytecode_path =
          _value;
      }
      if ( _index == 11 ) {
        contract_compiler_output_path =
          _value;
      }
      if ( _index == 12 ) {
        publication_namespace =
          _value;
      }
      if ( _index == 13 ) {
        file_hash =
          _value;
      }
      if ( _index == 14 ) {
        index_start =
          _value;
      }
      if ( _index == 15 ) {
        index_end =
          _value;
      }
      if ( _index == 16 ) {
        checkpoint_file_path =
          _value;
      }
      if ( 16 < _index ) {
	chunks_files_paths.push(
          _value);
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        quiet =
          "n";
        _usage(
          0);
      }
  });
  if ( file_hash == "" ||
       publication_namespace  == "" ||
       chunks_files_paths == [] ) {
    quiet =
      "n";
    _usage(
      1);
  }
}

async function
  _publish_cmdline(
    _app_opts) {
  let
    _chunk,
    _chunks_unverified,
    _index;
  try {
    await _publish.apply(
      null,
      _app_opts);
  } catch (e) {
    console.error(
      e);
    _msg_error(
      "Publication error.",
      1);
  }
}

function
  _overrides_set() {
  if ( call_timeout == "" ) {
    call_timeout =
      300;
  }
}

if ( _cmdline_check(
       "publish") == true ) {
  _global_variables();
  _cmdline_parse();
  _overrides_set();
  _config_show();
  app_opts = [
    retries_max,
    call_timeout,
    wallet_seed_path,
    api_key_path,
    target_network,
    contract_address,
    contract_abi_path,
    contract_bytecode_path,
    contract_compiler_output_path,
    publication_namespace,
    file_hash,
    index_start,
    index_end,
    checkpoint_file_path,
    chunks_files_paths,
  ];
  _publish_cmdline(
    app_opts);
}

module.exports = {
  _chunk_publish:
    _chunk_publish,
  _publish:
    _publish
};
